"""Deterministic, verifiable bundles for complete skill artifacts."""

from __future__ import annotations

import hashlib
import io
import json
import os
import stat
import zipfile
from dataclasses import dataclass
from pathlib import Path, PurePosixPath

import yaml

from skillctl.errors import SkillctlError
from skillctl.manifest import ManifestLoader, SkillManifest

ARTIFACT_SCHEMA = "skillctl.io/artifact/v1"
ARTIFACT_MEDIA_TYPE = "application/vnd.skillctl.artifact.v1+zip"
ARTIFACT_MANIFEST = "artifact.json"
MAX_ARTIFACT_FILES = 1_000
MAX_ARTIFACT_SIZE = 50 * 1024 * 1024

_EXCLUDED_DIRS = {
    ".git",
    ".hg",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".skillctl",
    ".svn",
    ".tox",
    ".venv",
    "__pycache__",
    "node_modules",
    "venv",
}
_EXCLUDED_FILES = {".DS_Store"}
_FIXED_ZIP_TIME = (1980, 1, 1, 0, 0, 0)


@dataclass(frozen=True)
class ArtifactFile:
    """One verified file in an artifact bundle."""

    path: str
    sha256: str
    size: int
    mode: int
    content: bytes


@dataclass(frozen=True)
class SkillArtifact:
    """A verified skill artifact and its package metadata."""

    name: str
    version: str
    content_hash: str
    manifest: dict
    files: tuple[ArtifactFile, ...]

    def file(self, path: str) -> ArtifactFile | None:
        """Return a file by its normalized bundle path."""
        return next((item for item in self.files if item.path == path), None)


def artifact_hash(bundle: bytes) -> str:
    """Return the immutable SHA-256 identity of an artifact bundle."""
    return hashlib.sha256(bundle).hexdigest()


def build_artifact(
    source_path: str | Path,
    manifest: SkillManifest,
    content: bytes,
) -> bytes:
    """Build a deterministic bundle from a validated skill source."""
    source = Path(source_path)
    root = source if source.is_dir() else source.parent
    files = _read_source_files(root)

    if "skill.yaml" not in files:
        files["skill.yaml"] = (
            yaml.safe_dump(manifest.to_dict(), sort_keys=False, allow_unicode=True).encode("utf-8"),
            0o644,
        )

    return build_artifact_from_files(manifest, content, files)


def build_minimal_artifact(manifest: SkillManifest, content: bytes) -> bytes:
    """Build a compatibility bundle when only manifest and content exist."""
    manifest_dict = manifest.to_dict()
    manifest_dict["spec"]["content"] = {"path": "SKILL.md"}
    manifest_bytes = yaml.safe_dump(
        manifest_dict,
        sort_keys=False,
        allow_unicode=True,
    ).encode("utf-8")
    files: dict[str, tuple[bytes, int]] = {"skill.yaml": (manifest_bytes, 0o644)}
    files["SKILL.md"] = (content, 0o644)
    return build_artifact_from_files(manifest, content, files)


def build_artifact_from_files(
    manifest: SkillManifest,
    content: bytes,
    files: dict[str, tuple[bytes, int]],
) -> bytes:
    """Build a deterministic bundle from an explicit file mapping."""
    normalized_files: dict[str, tuple[bytes, int]] = {}
    total_size = 0

    for raw_path, (file_content, raw_mode) in files.items():
        path = _normalize_path(raw_path)
        if path == ARTIFACT_MANIFEST:
            raise _artifact_error(
                "E_ARTIFACT_RESERVED_PATH",
                f"Source contains reserved path '{ARTIFACT_MANIFEST}'",
                "The artifact package manifest is generated by skillctl",
                f"Rename the source file '{ARTIFACT_MANIFEST}' and retry",
            )
        if path in normalized_files:
            raise _artifact_error(
                "E_ARTIFACT_DUPLICATE_PATH",
                f"Artifact contains duplicate path '{path}'",
                "Each artifact file must have one unique normalized path",
                "Remove or rename the duplicate file",
            )
        if not isinstance(file_content, bytes):
            raise TypeError(f"Artifact file content for {path!r} must be bytes")
        mode = 0o755 if raw_mode & 0o111 else 0o644
        normalized_files[path] = (file_content, mode)
        total_size += len(file_content)

    _enforce_limits(len(normalized_files), total_size)
    manifest_bytes = normalized_files.get("skill.yaml", (b"", 0))[0]
    if not manifest_bytes:
        raise _artifact_error(
            "E_ARTIFACT_MANIFEST_MISSING",
            "Artifact is missing skill.yaml",
            "Every immutable artifact must carry its parsed skill manifest",
            "Add skill.yaml or build the artifact through skillctl",
        )

    file_records = [
        {
            "mode": f"{mode:04o}",
            "path": path,
            "sha256": hashlib.sha256(file_content).hexdigest(),
            "size": len(file_content),
        }
        for path, (file_content, mode) in sorted(normalized_files.items())
    ]
    package_manifest = {
        "schemaVersion": ARTIFACT_SCHEMA,
        "mediaType": ARTIFACT_MEDIA_TYPE,
        "name": manifest.metadata.name,
        "version": manifest.metadata.version,
        "contentSha256": hashlib.sha256(content).hexdigest(),
        "manifestPath": "skill.yaml",
        "manifestSha256": hashlib.sha256(manifest_bytes).hexdigest(),
        "provenance": {
            "builder": "skillctl",
            "sourceType": "validated-skill",
        },
        "files": file_records,
    }
    package_bytes = (
        json.dumps(
            package_manifest,
            sort_keys=True,
            separators=(",", ":"),
            ensure_ascii=False,
        ).encode("utf-8")
        + b"\n"
    )

    output = io.BytesIO()
    with zipfile.ZipFile(output, "w", compression=zipfile.ZIP_STORED, strict_timestamps=True) as archive:
        _write_zip_entry(archive, ARTIFACT_MANIFEST, package_bytes, 0o644)
        for path, (file_content, mode) in sorted(normalized_files.items()):
            _write_zip_entry(archive, path, file_content, mode)
    return output.getvalue()


def inspect_artifact(
    bundle: bytes,
    *,
    expected_name: str | None = None,
    expected_version: str | None = None,
    expected_content: bytes | None = None,
) -> SkillArtifact:
    """Verify a bundle's structure, file hashes, manifest, and content binding."""
    try:
        archive = zipfile.ZipFile(io.BytesIO(bundle), "r")
    except (zipfile.BadZipFile, OSError) as exc:
        raise _artifact_error(
            "E_INVALID_ARTIFACT",
            "Artifact is not a valid ZIP bundle",
            str(exc),
            "Rebuild the artifact with skillctl",
        ) from exc

    with archive:
        infos = archive.infolist()
        if len(infos) > MAX_ARTIFACT_FILES + 1:
            _raise_limits(len(infos) - 1, sum(item.file_size for item in infos))

        by_path: dict[str, zipfile.ZipInfo] = {}
        for info in infos:
            path = _normalize_path(info.filename)
            if info.is_dir():
                raise _artifact_error(
                    "E_INVALID_ARTIFACT",
                    f"Artifact contains directory entry '{path}'",
                    "Canonical artifacts contain only regular file entries",
                    "Rebuild the artifact with skillctl",
                )
            if path in by_path:
                raise _artifact_error(
                    "E_ARTIFACT_DUPLICATE_PATH",
                    f"Artifact contains duplicate path '{path}'",
                    "Duplicate ZIP entries make artifact contents ambiguous",
                    "Rebuild the artifact without duplicate paths",
                )
            unix_mode = (info.external_attr >> 16) & 0xFFFF
            if stat.S_ISLNK(unix_mode):
                raise _artifact_error(
                    "E_ARTIFACT_SYMLINK",
                    f"Artifact contains symbolic link '{path}'",
                    "Links can escape the installation root during extraction",
                    "Replace the link with a regular file",
                )
            by_path[path] = info

        package_info = by_path.pop(ARTIFACT_MANIFEST, None)
        if package_info is None:
            raise _artifact_error(
                "E_INVALID_ARTIFACT",
                f"Artifact is missing {ARTIFACT_MANIFEST}",
                "The package manifest binds artifact identity and file hashes",
                "Rebuild the artifact with skillctl",
            )

        total_size = sum(item.file_size for item in by_path.values())
        _enforce_limits(len(by_path), total_size)
        try:
            package_manifest = json.loads(archive.read(package_info))
        except (json.JSONDecodeError, UnicodeDecodeError, OSError) as exc:
            raise _artifact_error(
                "E_INVALID_ARTIFACT",
                f"{ARTIFACT_MANIFEST} is not valid JSON",
                str(exc),
                "Rebuild the artifact with skillctl",
            ) from exc

        _validate_package_identity(package_manifest, expected_name, expected_version)
        records = package_manifest.get("files")
        if not isinstance(records, list):
            raise _artifact_error(
                "E_INVALID_ARTIFACT",
                "Artifact file inventory is missing or invalid",
                f"{ARTIFACT_MANIFEST}.files must be a list",
                "Rebuild the artifact with skillctl",
            )

        verified: list[ArtifactFile] = []
        declared_paths: set[str] = set()
        for record in records:
            item = _verify_file_record(record, archive, by_path, declared_paths)
            verified.append(item)

        extra_paths = set(by_path) - declared_paths
        if extra_paths:
            extra = sorted(extra_paths)[0]
            raise _artifact_error(
                "E_INVALID_ARTIFACT",
                f"Artifact contains undeclared file '{extra}'",
                "Every artifact file must be covered by the signed hash inventory",
                "Rebuild the artifact with skillctl",
            )

        file_map = {item.path: item for item in verified}
        manifest_path = package_manifest.get("manifestPath")
        manifest_file = file_map.get(manifest_path) if isinstance(manifest_path, str) else None
        if manifest_file is None:
            raise _artifact_error(
                "E_ARTIFACT_MANIFEST_MISSING",
                "Artifact manifest file is missing",
                "manifestPath does not name a declared artifact file",
                "Rebuild the artifact with skillctl",
            )
        if hashlib.sha256(manifest_file.content).hexdigest() != package_manifest.get("manifestSha256"):
            raise _artifact_error(
                "E_ARTIFACT_INTEGRITY",
                "Artifact manifest hash does not match",
                "skill.yaml differs from the package manifest binding",
                "Reject the artifact and publish a clean version",
            )

        parsed_manifest = _parse_artifact_manifest(manifest_file.content)
        name = package_manifest.get("name")
        version = package_manifest.get("version")
        if parsed_manifest.metadata.name != name or parsed_manifest.metadata.version != version:
            raise _artifact_error(
                "E_ARTIFACT_IDENTITY",
                "Artifact identity does not match skill.yaml",
                "Package and skill manifest names and versions must be identical",
                "Rebuild the artifact from the intended skill version",
            )

        content_hash = package_manifest.get("contentSha256")
        resolved_content = _resolve_artifact_content(parsed_manifest, file_map)
        if hashlib.sha256(resolved_content).hexdigest() != content_hash:
            raise _artifact_error(
                "E_ARTIFACT_INTEGRITY",
                "Artifact content binding does not match skill.yaml",
                "The resolved skill content differs from contentSha256",
                "Reject the artifact and publish a clean version",
            )
        if expected_content is not None and hashlib.sha256(expected_content).hexdigest() != content_hash:
            raise _artifact_error(
                "E_ARTIFACT_CONTENT_MISMATCH",
                "Uploaded artifact does not match uploaded skill content",
                "The artifact binds a different resolved content digest",
                "Upload content and artifact generated from the same validated skill",
            )

        canonical = build_artifact_from_files(
            parsed_manifest,
            resolved_content,
            {item.path: (item.content, item.mode) for item in verified},
        )
        if bundle != canonical:
            raise _artifact_error(
                "E_ARTIFACT_NON_CANONICAL",
                "Artifact ZIP encoding is not canonical",
                "Immutable artifact identity requires deterministic metadata, ordering, and storage",
                "Rebuild the artifact with skillctl before publishing",
            )

        return SkillArtifact(
            name=name,
            version=version,
            content_hash=content_hash,
            manifest=package_manifest,
            files=tuple(verified),
        )


def extract_artifact(
    bundle: bytes,
    target: str | Path,
    *,
    overwrite: bool = False,
    expected_name: str | None = None,
    expected_version: str | None = None,
) -> SkillArtifact:
    """Verify and safely extract an artifact's declared files."""
    artifact = inspect_artifact(
        bundle,
        expected_name=expected_name,
        expected_version=expected_version,
    )
    destination = Path(target)
    destination.mkdir(parents=True, exist_ok=True)

    for item in artifact.files:
        output = destination.joinpath(*PurePosixPath(item.path).parts)
        if output.exists() and not overwrite:
            raise _artifact_error(
                "E_ARTIFACT_FILE_EXISTS",
                f"Refusing to overwrite '{output}'",
                "Artifact extraction is non-destructive by default",
                "Choose an empty destination or explicitly enable overwrite",
            )
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_bytes(item.content)
        output.chmod(item.mode)
    return artifact


def _read_source_files(root: Path) -> dict[str, tuple[bytes, int]]:
    if not root.is_dir():
        raise _artifact_error(
            "E_ARTIFACT_SOURCE",
            f"Artifact source directory does not exist: {root}",
            "A complete artifact must be built from a skill directory",
            "Provide the skill directory, skill.yaml, or SKILL.md path",
        )

    files: dict[str, tuple[bytes, int]] = {}
    total_size = 0
    for current, dir_names, file_names in os.walk(root, followlinks=False):
        current_path = Path(current)
        kept_dirs: list[str] = []
        for name in sorted(dir_names):
            child = current_path / name
            if name in _EXCLUDED_DIRS:
                continue
            if child.is_symlink():
                raise _artifact_error(
                    "E_ARTIFACT_SYMLINK",
                    f"Artifact source contains symbolic link '{child.relative_to(root)}'",
                    "Links make artifact contents dependent on files outside the skill",
                    "Replace the link with a regular file or directory",
                )
            kept_dirs.append(name)
        dir_names[:] = kept_dirs

        for name in sorted(file_names):
            if name in _EXCLUDED_FILES:
                continue
            path = current_path / name
            relative = path.relative_to(root).as_posix()
            if path.is_symlink():
                raise _artifact_error(
                    "E_ARTIFACT_SYMLINK",
                    f"Artifact source contains symbolic link '{relative}'",
                    "Links make artifact contents dependent on files outside the skill",
                    "Replace the link with a regular file",
                )
            if not path.is_file():
                raise _artifact_error(
                    "E_ARTIFACT_FILE_TYPE",
                    f"Artifact source contains unsupported file '{relative}'",
                    "Only regular files can be packaged",
                    "Remove special filesystem entries and retry",
                )
            file_content = path.read_bytes()
            total_size += len(file_content)
            files[relative] = (file_content, stat.S_IMODE(path.stat().st_mode))
            _enforce_limits(len(files), total_size)
    return files


def _normalize_path(raw_path: object) -> str:
    if not isinstance(raw_path, str) or not raw_path or "\x00" in raw_path or "\\" in raw_path:
        raise _unsafe_path(raw_path)
    path = PurePosixPath(raw_path)
    if path.is_absolute() or any(part in {"", ".", ".."} for part in path.parts):
        raise _unsafe_path(raw_path)
    return path.as_posix()


def _unsafe_path(raw_path: object) -> SkillctlError:
    return _artifact_error(
        "E_ARTIFACT_PATH",
        f"Unsafe artifact path '{raw_path}'",
        "Artifact paths must be normalized, relative POSIX paths without traversal",
        "Remove absolute, parent, current-directory, or backslash path segments",
    )


def _write_zip_entry(archive: zipfile.ZipFile, path: str, content: bytes, mode: int) -> None:
    info = zipfile.ZipInfo(path, date_time=_FIXED_ZIP_TIME)
    info.compress_type = zipfile.ZIP_STORED
    info.create_system = 3
    info.external_attr = (stat.S_IFREG | mode) << 16
    archive.writestr(info, content)


def _validate_package_identity(
    package_manifest: object,
    expected_name: str | None,
    expected_version: str | None,
) -> None:
    if not isinstance(package_manifest, dict):
        raise _artifact_error(
            "E_INVALID_ARTIFACT",
            f"{ARTIFACT_MANIFEST} must be a JSON object",
            "The package manifest has an invalid top-level type",
            "Rebuild the artifact with skillctl",
        )
    if (
        package_manifest.get("schemaVersion") != ARTIFACT_SCHEMA
        or package_manifest.get("mediaType") != ARTIFACT_MEDIA_TYPE
    ):
        raise _artifact_error(
            "E_ARTIFACT_SCHEMA",
            "Artifact schema or media type is unsupported",
            "This skillctl version only accepts the v1 artifact contract",
            "Rebuild with a compatible skillctl version",
        )
    name = package_manifest.get("name")
    version = package_manifest.get("version")
    content_hash = package_manifest.get("contentSha256")
    if not isinstance(name, str) or not name or not isinstance(version, str) or not version:
        raise _artifact_error(
            "E_ARTIFACT_IDENTITY",
            "Artifact name or version is missing",
            "Immutable artifacts require a concrete name and version",
            "Rebuild the artifact from a valid skill manifest",
        )
    if (
        not isinstance(content_hash, str)
        or len(content_hash) != 64
        or any(character not in "0123456789abcdef" for character in content_hash)
    ):
        raise _artifact_error(
            "E_INVALID_ARTIFACT",
            "Artifact content digest is missing or invalid",
            "contentSha256 must be a SHA-256 hexadecimal digest",
            "Rebuild the artifact with skillctl",
        )
    if expected_name is not None and name != expected_name:
        raise _artifact_error(
            "E_ARTIFACT_IDENTITY",
            f"Artifact name '{name}' does not match expected name '{expected_name}'",
            "Uploaded package and manifest identify different skills",
            "Upload the artifact generated for the expected skill",
        )
    if expected_version is not None and version != expected_version:
        raise _artifact_error(
            "E_ARTIFACT_IDENTITY",
            f"Artifact version '{version}' does not match expected version '{expected_version}'",
            "Uploaded package and manifest identify different versions",
            "Upload the artifact generated for the expected version",
        )


def _verify_file_record(
    record: object,
    archive: zipfile.ZipFile,
    by_path: dict[str, zipfile.ZipInfo],
    declared_paths: set[str],
) -> ArtifactFile:
    if not isinstance(record, dict):
        raise _artifact_error(
            "E_INVALID_ARTIFACT",
            "Artifact file inventory contains a non-object entry",
            "Every file record must define path, hash, size, and mode",
            "Rebuild the artifact with skillctl",
        )
    path = _normalize_path(record.get("path"))
    if path == ARTIFACT_MANIFEST or path in declared_paths:
        raise _artifact_error(
            "E_ARTIFACT_DUPLICATE_PATH",
            f"Artifact declares path '{path}' more than once",
            "Each artifact file must have one unique inventory record",
            "Rebuild the artifact without duplicate paths",
        )
    info = by_path.get(path)
    if info is None:
        raise _artifact_error(
            "E_ARTIFACT_FILE_MISSING",
            f"Declared artifact file '{path}' is missing",
            "The ZIP contents do not match the package inventory",
            "Reject the artifact and publish a complete bundle",
        )
    content = archive.read(info)
    digest = hashlib.sha256(content).hexdigest()
    raw_size = record.get("size")
    raw_mode = record.get("mode")
    try:
        if not isinstance(raw_size, int) or isinstance(raw_size, bool) or not isinstance(raw_mode, str):
            raise ValueError("size must be an integer and mode must be an octal string")
        declared_size = raw_size
        declared_mode = int(raw_mode, 8)
    except (TypeError, ValueError) as exc:
        raise _artifact_error(
            "E_INVALID_ARTIFACT",
            f"Artifact metadata for '{path}' has invalid size or mode",
            str(exc),
            "Rebuild the artifact with skillctl",
        ) from exc
    if digest != record.get("sha256") or len(content) != declared_size:
        raise _artifact_error(
            "E_ARTIFACT_INTEGRITY",
            f"Artifact integrity check failed for '{path}'",
            "File bytes do not match their declared hash or size",
            "Reject the artifact and publish a clean version",
        )
    if declared_mode not in {0o644, 0o755}:
        raise _artifact_error(
            "E_INVALID_ARTIFACT",
            f"Artifact mode for '{path}' is unsupported",
            "Canonical artifacts only allow regular files with mode 0644 or 0755",
            "Rebuild the artifact with skillctl",
        )
    declared_paths.add(path)
    return ArtifactFile(
        path=path,
        sha256=digest,
        size=len(content),
        mode=declared_mode,
        content=content,
    )


def _parse_artifact_manifest(content: bytes) -> SkillManifest:
    try:
        raw = yaml.safe_load(content.decode("utf-8"))
        if not isinstance(raw, dict):
            raise ValueError("skill.yaml is not a mapping")
        return ManifestLoader()._dict_to_manifest(raw)
    except (UnicodeDecodeError, yaml.YAMLError, ValueError, TypeError) as exc:
        raise _artifact_error(
            "E_INVALID_ARTIFACT",
            "Artifact skill.yaml is invalid",
            str(exc),
            "Rebuild the artifact from a valid skill manifest",
        ) from exc


def _resolve_artifact_content(
    manifest: SkillManifest,
    files: dict[str, ArtifactFile],
) -> bytes:
    if manifest.spec.content.inline is not None:
        return manifest.spec.content.inline.encode("utf-8")
    if manifest.spec.content.path:
        path = _normalize_path(manifest.spec.content.path)
        item = files.get(path)
        if item is None:
            raise _artifact_error(
                "E_ARTIFACT_FILE_MISSING",
                f"Skill content file '{path}' is missing from artifact",
                "skill.yaml references a file that is not in the package inventory",
                "Include the referenced content file and rebuild",
            )
        return item.content
    return b""


def _enforce_limits(file_count: int, total_size: int) -> None:
    if file_count > MAX_ARTIFACT_FILES or total_size > MAX_ARTIFACT_SIZE:
        _raise_limits(file_count, total_size)


def _raise_limits(file_count: int, total_size: int) -> None:
    raise _artifact_error(
        "E_ARTIFACT_TOO_LARGE",
        "Artifact exceeds package limits",
        (
            f"Found {file_count} files and {total_size} bytes; limits are "
            f"{MAX_ARTIFACT_FILES} files and {MAX_ARTIFACT_SIZE} bytes"
        ),
        "Remove generated, cached, or unnecessary large files and retry",
    )


def _artifact_error(code: str, what: str, why: str, fix: str) -> SkillctlError:
    return SkillctlError(code=code, what=what, why=why, fix=fix)
